### ISSUE TITLE
Release the first Alpha version with Netty 5 Alpha3?

### ISSUE THREAD

**Issue by violetagg** [netty-contrib/codec-haproxy#10]
@chrisvest @normanmaurer We already have Netty 5 Alpha3 released. What do you think about releasing the first Alpha version for this module?

**Comment by violetagg** [comment]
@chrisvest @normanmaurer I plan to release Reactor Netty based on Netty 5 Alpha3 and I need this module also released.
Can I help somehow with the release?

**Comment by chrisvest** [comment]
I think it's a good idea to do a release. Likewise for the other modules.
Are you able to run the Release workflow from the Actions tab?

**Comment by chrisvest** [comment]
Maybe I should first give it a try myself, to make sure the process works.

**Comment by chrisvest** [comment]
Looks like the process is broken. I'll try to fix it.

**Comment by chrisvest** [comment]
The release process should be fixed now, but one thing to keep in mind is that javadocs are stricter now, so it might fail on that. You can check before hand by running `mvn clean install -DperformRelease`, which will also generate javadocs, or fail on javadoc errors as the case may be.

**Comment by violetagg** [comment]
@chrisvest The javadoc for this project is OK.

> Are you able to run the Release workflow from the Actions tab?

I don't see on Actions tab any possibility to run the Release workflow

**Comment by chrisvest** [comment]
Ok, I don't know if it's a permission issue or something.

I released 5.0.0.Alpha1.

**Comment by violetagg** [comment]
@chrisvest thanks a lot
